version: '3.1'

services:

  db:
    image: mysql:8.0.19

    # ports:
    #   - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysafepass
      MYSQL_DATABASE: test_project
    volumes:
    - ./docker/db-data:/var/lib/mysql 

  myjavaapp:
    build: ./
    image: rest-spring:0.13
    # environment:
    #   - APP_ENV=dev
    ports:
      - 8337:8080